# Generated by Django 5.2 on 2025-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerstockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerstock',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
