# Generated by Django 5.2 on 2025-05-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
