# Generated by Django 5.2 on 2025-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsapp', '0002_rename_full_name_account_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgers',
            old_name='ledger_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
